// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingSystem.Models;
using VotingSystem.Models.Data;

namespace VotingSystem.Migrations
{
    [DbContext(typeof(VotingSystemDbContext))]
    [Migration("20210125211047_AddedVote")]
    partial class AddedVote
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EditionDraftProject", b =>
                {
                    b.Property<int>("EditionDraftsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("EditionDraftsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("EditionDraftProject");
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ActiveEditions");
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEditionParticipant", b =>
                {
                    b.Property<int>("ActiveEditionId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ActiveEditionId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ActiveEditionParticipant");
                });

            modelBuilder.Entity("VotingSystem.Models.EditionDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EditionDrafts");
                });

            modelBuilder.Entity("VotingSystem.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("PricePln")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.Property<int>("ActiveEditionId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("VoterPesel")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActiveEditionId", "ProjectId", "VoterPesel");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("EditionDraftProject", b =>
                {
                    b.HasOne("VotingSystem.Models.EditionDraft", null)
                        .WithMany()
                        .HasForeignKey("EditionDraftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEditionParticipant", b =>
                {
                    b.HasOne("VotingSystem.Models.ActiveEdition", null)
                        .WithMany("Participants")
                        .HasForeignKey("ActiveEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.HasOne("VotingSystem.Models.ActiveEditionParticipant", null)
                        .WithMany("Votes")
                        .HasForeignKey("ActiveEditionId", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEdition", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEditionParticipant", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
