// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingSystem.Models;
using VotingSystem.Models.Data;

namespace VotingSystem.Migrations
{
    [DbContext(typeof(VotingSystemDbContext))]
    [Migration("20210126123908_MergingEditionTables_MergingParticipantTables")]
    partial class MergingEditionTables_MergingParticipantTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EditionDraftProject", b =>
                {
                    b.Property<int>("EditionDraftsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("EditionDraftsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("EditionDraftProject");
                });

            modelBuilder.Entity("VotingSystem.Models.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Edition");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Edition");
                });

            modelBuilder.Entity("VotingSystem.Models.EditionDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EditionDrafts");
                });

            modelBuilder.Entity("VotingSystem.Models.EditionParticipant", b =>
                {
                    b.Property<int?>("EditionId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("EditionId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EditionParticipant");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EditionParticipant");
                });

            modelBuilder.Entity("VotingSystem.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("PricePln")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EditionId")
                        .HasColumnType("int");

                    b.Property<int?>("EditionParticipantEditionId")
                        .HasColumnType("int");

                    b.Property<int?>("EditionParticipantProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("VoterPesel")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EditionParticipantEditionId", "EditionParticipantProjectId");

                    b.HasIndex("EditionId", "ProjectId", "VoterPesel")
                        .IsUnique()
                        .HasFilter("[VoterPesel] IS NOT NULL");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEdition", b =>
                {
                    b.HasBaseType("VotingSystem.Models.Edition");

                    b.HasDiscriminator().HasValue("ActiveEdition");
                });

            modelBuilder.Entity("VotingSystem.Models.ConcludedEdition", b =>
                {
                    b.HasBaseType("VotingSystem.Models.Edition");

                    b.HasDiscriminator().HasValue("ConcludedEdition");
                });

            modelBuilder.Entity("VotingSystem.Models.ActiveEditionParticipant", b =>
                {
                    b.HasBaseType("VotingSystem.Models.EditionParticipant");

                    b.HasDiscriminator().HasValue("ActiveEditionParticipant");
                });

            modelBuilder.Entity("VotingSystem.Models.ConcludedEditionParticipant", b =>
                {
                    b.HasBaseType("VotingSystem.Models.EditionParticipant");

                    b.HasDiscriminator().HasValue("ConcludedEditionParticipant");
                });

            modelBuilder.Entity("EditionDraftProject", b =>
                {
                    b.HasOne("VotingSystem.Models.EditionDraft", null)
                        .WithMany()
                        .HasForeignKey("EditionDraftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotingSystem.Models.EditionParticipant", b =>
                {
                    b.HasOne("VotingSystem.Models.Edition", null)
                        .WithMany("Participants")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotingSystem.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VotingSystem.Models.Vote", b =>
                {
                    b.HasOne("VotingSystem.Models.EditionParticipant", null)
                        .WithMany("Votes")
                        .HasForeignKey("EditionParticipantEditionId", "EditionParticipantProjectId");
                });

            modelBuilder.Entity("VotingSystem.Models.Edition", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("VotingSystem.Models.EditionParticipant", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
